# Configuration file for Wanderer Linux Updater
# This file contains all configuration options for the updater

# Firmware sync configuration
firmware:
  # Source URL for firmware list
  source_url: "https://od.lk/d/MzNfMzIzNTQ2OTNf/FirmwareDownloadList.txt"
  
  # GitHub repository for hosting firmware files (optional)
  github_repo: "grm/wanderer-linux-updater"
  
  # Sync interval in hours (for GitHub Actions)
  sync_interval_hours: 6
  
  # Firmware directory name
  firmware_dir: "firmwares"
  
  # Index file name
  index_file: "firmware_index.json"

# Device detection configuration (for port detection and handshake testing)
device_detection:
  # Handshake timeout in seconds
  handshake_timeout: 5
  
  # Serial port detection timeout in seconds
  port_detection_timeout: 3
  
  # Baud rates to try during handshake
  baud_rates: [115200, 57600, 9600]
  
  # Handshake commands to send
  handshake_commands:
    - "VERSION"
    - "DEVICE"
    - "ID"

# Device definitions (replaces devices.txt)
devices:
  WandererRotatorMini:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    
  WandererRotatorLiteV1:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    
  WandererRotatorLiteV2:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    
  WandererRotatorProV1:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    
  WandererBoxPlusV2:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "XXX"
    
  WandererBoxUltimateV2:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_string: "XXX"
    
  WandererCoverV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    # Device responds to handshake_string command
    
  WandererBoxPlusV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "ZXWBPlusV3"
    
  WandererBoxProV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "ZXWBProV3"
    
  WandererCoverV4:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    # No handshake_string = device sends automatic response on connection
    
  WandererCoverV4Pro:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    # No handshake_string = device sends automatic response on connection
    
  WandererDewTerminator:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "XXX"
    
  WandererEclipse:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "XXX"
    
  WandererRotatorProV2:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "1500001"
    
  WandererETA54:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_string: "XXX"

# Update configuration
update:
  # Default timeout for avrdude operations
  avrdude_timeout: 60
  
  # Dry run mode (default: false)
  dry_run: false
  
  # Confirm before update (default: true)
  confirm_update: true

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  
  # Log to file (optional)
  log_file: null
  
  # Show progress bars
  show_progress: true 