# Configuration file for Wanderer Linux Updater
# This file contains all configuration options for the updater

# Firmware sync configuration
firmware:
  # GitHub repository for hosting firmware files (optional)
  github_repo: "grm/wanderer-linux-updater"
  
  # Sync interval in hours (for GitHub Actions)
  sync_interval_hours: 6
  
  # Firmware directory name
  firmware_dir: "firmwares"
  
  # Index file name
  index_file: "firmware_index.json"

# Device detection configuration (for testing and debugging)
device_detection:
  # Handshake timeout in seconds
  handshake_timeout: 5
  
  # Serial port detection timeout in seconds
  port_detection_timeout: 3

# Device definitions (replaces devices.txt)
devices:
  WandererRotatorMini:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "WandererRotatorMini"
    
  WandererRotatorLiteV1:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "WandererRotatorLite"
    
  WandererRotatorLiteV2:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "WandererRotatorLiteV2"
    
  WandererRotatorProV1:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "XXX"
    
  WandererBoxPlusV2:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "XXX"
    handshake_response: "XXX"
    
  WandererBoxUltimateV2:
    avr_device: "m328p"
    programmer: "arduino"
    baud_rate: 57600
    handshake_baud_rate: 19200
    handshake_command: "XXX"
    handshake_response: "XXX"
    
  WandererCoverV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "WandererCoverV3"
    
  WandererBoxPlusV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_response: "ZXWBPlusV3"
    
  WandererBoxProV3:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_response: "ZXWBProV3"
    
  WandererCoverV4:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    # No handshake_command = device sends automatic response on connection
    handshake_response: "WandererCoverV4"
    
  WandererCoverV4Pro:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    # No handshake_command = device sends automatic response on connection
    handshake_response: "XXX"
    
  WandererDewTerminator:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "XXX"
    handshake_response: "XXX"
    
  WandererEclipse:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "1500001"
    handshake_response: "WandererEclipse"
    
  WandererRotatorProV2:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "XXX"
    handshake_response: "XXX"
    
  WandererETA54:
    avr_device: "m168p"
    programmer: "arduino"
    baud_rate: 115200
    handshake_baud_rate: 19200
    handshake_command: "XXX"
    handshake_response: "XXX"

# Update configuration
update:
  # Default timeout for avrdude operations
  avrdude_timeout: 60
  
  # Dry run mode (default: false)
  dry_run: false
  
  # Confirm before update (default: true)
  confirm_update: true

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  
  # Log to file (optional)
  log_file: null
  
  # Show progress bars
  show_progress: true 